version: "3.8"  
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql
    user: root
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: Test1234_
    ports:
    - 1433:1433
    volumes:
    - ./docker/sql/mssql/data:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P test1234 -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 30s
      retries: 3