version: "3.8"
name: "api_without_sql"

services:

  api:
    container_name: apiRest
    build: "./"
    env_file:
      - ./.env
    environment:
      PORT: $PORT
    restart: on-failure
    expose:
      - "$PORT"
    ports:
      - "3001-3005:$PORT"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          cpus: "1"
          memory: 256m
        reservations:
          cpus: "0.5"
          memory: 128m  
    

networks:
  overlay: